varsion: '3.8'
services:
  data:
    countainer_name: data
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    network:
      - todonetwork
    volumes:
      - 'mogodata:/data/db'
  todos:
    countainer_name: todos
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5551:3001'
    environment:
      - PORT=3001
      - CONNECTION_STRING=mongodb://root:root@data:27017/main_db
    depends_on:
      - data
    network:
      - todonetwork
  networks:
    todonetwork: null
  volumes:
    mogodata: null